// Tiny token compiler: primitive -> semantic -> component, emitted as CSS variables.
// References like {color.blue.600} become var(--color-blue-600), so themes swap at runtime.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const read = (f) => JSON.parse(readFileSync(new URL(`./src/${f}.json`, import.meta.url), 'utf8'));
const flat = (o, p = []) =>
  Object.entries(o).flatMap(([k, v]) =>
    v && typeof v === 'object' && !('$value' in v) ? flat(v, [...p, k]) : [[[...p, k].join('-'), v.$value]]);
const ref = (v) => String(v).replace(/\{([^}]+)\}/g, (_, p) => `var(--${p.replaceAll('.', '-')})`);
const decl = (pairs) => pairs.map(([k, v]) => `  --${k}: ${ref(v)};`).join('\n');

const prim = flat(read('primitive'));
const sem = read('semantic');
const light = flat(sem.light);
const dark = flat(sem.dark);
const comp = flat(read('component'));

const css = `/* Generated by build.mjs - do not edit. */
:root {
${decl(prim)}
${decl(light)}
${decl(comp)}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${decl(dark)}
  }
}
:root[data-theme="dark"] {
${decl(dark)}
}
`;
const names = light.map(([k]) => k);
const preset = `export default { theme: { extend: { colors: ${JSON.stringify(
  Object.fromEntries(names.map((n) => [n.replace(/^color-/, ''), `var(--${n})`])), null, 2)} } } };\n`;

mkdirSync(new URL('./dist/', import.meta.url), { recursive: true });
writeFileSync(new URL('./dist/tokens.css', import.meta.url), css);
writeFileSync(new URL('./dist/tailwind-preset.js', import.meta.url), preset);
writeFileSync(new URL('./dist/tokens.json', import.meta.url), JSON.stringify({ primitive: Object.fromEntries(prim), light: Object.fromEntries(light), dark: Object.fromEntries(dark), component: Object.fromEntries(comp) }, null, 2));
console.log(`tokens: ${prim.length} primitive, ${light.length} semantic (x2 themes), ${comp.length} component`);
